# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bdf388ba7b50164d852a8d92b999796bfdb3c26d164fe2cdae5de9d6f1bf0dc9c50893bf3a8502f39b57857e990ee14a9101d7c4b3d8c4d70cce048a8c7dad4

test:
  secret_key_base: 545ebb7a3ffe9231cdd4cceb9d2242103bedd2b786b7e38eb0b06aabfc9e4d44501897dcec5a542951c3a5b151bc07fb0cfd88c163465bc787bb5c6ecc998cd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
# Can do it since it is just to learn!
  secret_key_base: d5050d301ce389c0978a6413d5170e9d0521390dd37f8eeb0a4bb3667edc9a002ab7872bd81a152cd5195fe78922a6d033aea0b9b232d27b21a1aeb97c1bb348
